# Generated by Django 5.2.1 on 2025-05-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citysearch',
            name='user',
        ),
        migrations.AlterField(
            model_name='citysearch',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='citysearch',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
