# Generated by Django 5.2.1 on 2025-05-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_remove_citysearch_user_alter_citysearch_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citysearch',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='citysearch',
            name='session_key',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='citysearch',
            unique_together={('city', 'session_key')},
        ),
    ]
